apiVersion: v1
kind: Service
metadata:
  name: income-predictor-service
spec:
  type: LoadBalancer
  selector:
    app: income-predictor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
